name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Maven
        run: >
          ./mvnw $MAVEN_CLI_OPTS
          clean verify
      - name: Extract release tag
        id: vars
        run: echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: keycloak-metrics-spi ${{ steps.vars.outputs.version }}
          files: |
            ./target/keycloak-metrics-spi-*.jar
